version: '3.8'
services:
  app:
    build:
      context: .
      target: base
    ports: 
      - 9876:9876
    volumes:
      - .:/app
      - ./nodemon.json:/app/nodemon.json
      - /app/node_modules
    command: npm run dev
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017 
  mongo:
    image: mongo
    ports:
      - 27017:27017